import { Component, Inject, ViewChild } from '@angular/core';
// Imports:
import { HeroesService } from 'src/app/services/heroes.service';
import { Observable } from 'rxjs';
import { MatTableDataSource, MatTableModule} from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { MatSortModule, MatSort, Sort} from '@angular/material/sort';

@Component({
  selector: 'app-hero-list',
  templateUrl: './hero-list.component.html',
  styleUrls: ['./hero-list.component.css']
})
export class HeroListComponent {

  // Service injection:
  constructor (
    private heroesService: HeroesService,
    // In strict mode, all variables must be initialized,
    // so 'heroes' is declared as public, inside the constructor
    @Inject(HeroesService) public heroes: Observable<any>, // Inject decorator is necessary for the dependency to work
    ) {}

  // Calculating total amount of required data arrays:
  totalHeroes = 2708;
  splitHeroes = 2708 / 100;
  totalArrays = Math.round(this.splitHeroes); // +1
  
  // Data variables for Material Table:
  displayedColumns: string [] = ['Heroes'];
  dataSource: any = new MatTableDataSource();
  dataArray = [];

  // Variables for URL generation:
  PUBLIC_KEY = 'ddbe649e8f64b8a35ba2a6203c2e9b86';
  // HASH is generated by passing this string combination: 1 + Private Key + Public Key
  // through a MD5 Hash Generator ( https://letmegooglethat.com/?q=MD5+hash+generator )
  // The Public and Private Keys are provided by the API ( https://developer.marvel.com/ )
  HASH = '1c820bbadd4cd42eb3139d95fe35aa64';
  OFFSET = 0; // URL parameter: controls the amount of elements skipped per call
  URL_API = `https:gateway.marvel.com/v1/public/characters?ts=1&apikey=${this.PUBLIC_KEY}&hash=${this.HASH}&offset=${this.OFFSET}&limit=100`; // '&limit=100' controls amount of elements returned (max 100 per call)
  //URL_API_2 = `https:gateway.marvel.com/v1/public/characters?ts=1&apikey=${this.PUBLIC_KEY}&hash=${this.HASH}&offset=100&limit=100`;

  // Additional Mat Table functionalities:
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  // ------------------------------------------------------------
  // ============================================================
  // ------------------------------------------------------------

  ngOnInit() {
    this.initializeDataArray();
    this.getHeroes();
    //this.getHeroes200();
  }

  ngAfterViewInit() { 
    // This must be executed after data loads
    // in order for Paginator to work properly:
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  // Method for getting a list with all Marvel heroes
  // Data is stored in 'heroes'
  getHeroes(){

  //for (let i = 0; i < this.totalArrays; i+100) {  
    
    this.OFFSET = 200;
    this.heroes = this.heroesService.getAllHeroes(this.URL_API);  // Subscription to Observable won't be used here because the 'async' pipe will be used in the HTML template
    this.heroes.forEach(element => this.dataArray[0].data = element);
    //}

    console.log("Heroes Data Array: ", this.dataArray);

  }

  /*
  getHeroes200(){
    this.heroes = this.heroesService.getAllHeroes200();
    this.heroes.forEach(element => this.dataArray1.data = element);

    console.log("Heroes 2: ", this.dataArray1);
  } */

  initializeDataArray() {
    for (var i = 0; i < this.totalArrays; ++i) {
      this.dataArray[i] = new MatTableDataSource();
    }
  }

  /*
  fusionarData() {
    //this.dataSource.data.push(this.dataArray1.data);
    for (let i = 0; i < this.dataArray1.data.length; i++) {
      this.dataSource.data.push(this.dataArray1.data[i]);
    }

    console.log("Heroes MIX: ", this.dataSource);
    console.log("Heroe Nro 200: ", this.dataSource.data[199]);
  }
  */
  
  // ---------- [ TABLE SEARCH FILTER ] ----------

  filterData ($event: any){
    this.dataSource.filter = $event.target.value;
  }

}